apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-agent

resources:
  - namespace.yaml
  - rbac.yaml
  - mcpserver.yaml

commonLabels:
  app.kubernetes.io/name: dm-nkp-gitops-kmcp-server
  app.kubernetes.io/part-of: gitops-monitoring

images:
  - name: ghcr.io/deepak-muley/dm-nkp-gitops-kmcp-server
    newTag: "0.1.0"
